if ( GetLocale() == "zhCN" ) then

LC_ROTATION_TPS = "TPS：技能循环";
LC_ROTATION_TPS_DESCRIPTION = "设置每秒技能循环的响应次数";
LC_UNITS_TPS = "TPS：单位扫描";
LC_UNITS_TPS_DESCRIPTION = "设置每秒对附近单位的分析次数";

--RotationOptions Common
LC_ARCANE_TORRENT = "奥术洪流"
LC_ARCANE_TORRENT_DESCRIPTION = "|cffFFBB00自动使用奥术洪流"
LC_ARTIFACT = "神器"
LC_ARTIFACT_CD = "大技能"
LC_ARTIFACT_EVERY_TIME = "任何时候"
LC_AUTO_FACING = "自动面向目标"
LC_AUTO_FACING_DESCRIPTION = "自动面向目标";
LC_AUTO_TARGET = "自动选择目标";
LC_AUTO_TARGET_DESCRIPTION = "自动选择目标";
LC_BERSERKING = "嗜血术";
LC_BERSERKING_DESCRIPTION = "|cffFFBB00自动使用嗜血术";
LC_BLOOD_FURY = "血之狂怒";
LC_BLOOD_FURY_DESCRIPTION = "|cffFFBB00自动使用血之狂怒";
LC_COOLDOWNS = "大技能";
LC_DEADLY_GRACE = "|cffFFFF00致命优雅";
LC_DEFENSIVE = "自保";
LC_DOT_MINIMUM_HEALTH = "Dot最小血量";
LC_DOT_MINIMUM_HEALTH_DESCRIPTION = "|cffFFBB00多线输出下Dot施放最小血量（百万）";
LC_FLASK = "合剂";
LC_GENERAL = "常规";
LC_INTERRUPTS = "打断";
LC_INTERRUPTS_AT = "打断位置";
LC_INTERRUPTS_AT_DESCRIPTION = "|cffFFFFFF在施法百分比打断，0为随机百分比";
LC_OLD_WAR = "|cffFFFF00上古战神";
LC_POTION = "爆发药水";
LC_PRE_PULL_BOSSMOD = "BOSS开怪前准备";
LC_PRE_PULL_TIMER = "开怪倒计时";
LC_PRE_PULL_TIMER_DESCRIPTION =  "|cffFFFFFF在开怪倒计时到达多少秒时进行准备（需要DBM）";
LC_PROLONGED_POWER = "|cff00BB00延时之力";

--Priest
LC_BODY_AND_SOUL = "身心合一";
LC_BODY_AND_SOUL_DESCRIPTION = "|cffFFBB00在玩家移动时，延时n秒使用|cffFF0000真言术：盾|cffFFBB00来触发身心合一。S2M时无效";

--Shawdow Priest
LC_BLESSED_DAWNLIGHT_MEDALLION = "使用项链"
LC_BLESSED_DAWNLIGHT_MEDALLION_DESCRIPTION = "|cffFFBB00在开启自杀后下一个GCD将会死亡前自动使用项链"
LC_DISPERSION = "影散"
LC_DISPERSION_DESCRIPTION = "|cffFFBB00让系统自动判断使用影散的时机"
LC_EXECUTE_ACTORS = "带斩杀队友数";
LC_EXECUTE_ACTORS_DESCRIPTION = "带斩杀队友数（包括自己）";
LC_MINDBENDER_SHADOWFIEND = "摧心魔/暗影魔"
LC_POWER_INFUSION = "能量灌注"
LC_S2M_CHECK = "预估自杀秒数";
LC_S2M_CHECK_DESCRIPTION = "预估自杀的可持续秒数";
LC_SWP_MAX_TARGETS = "多目标 暗言术：痛";
LC_SWP_MAX_TARGETS_DESCRIPTION = "|cffFFBB00暗言术：痛 目标上限";
LC_TIME_TO_USE_POWER_INFUSION = "开启能量灌注的时机"
LC_TIME_TO_USE_POWER_INFUSION_DESCRIPTION = "|cffFFBB00开启能量灌注的时机，以秒为单位，并不一定等于当前层数"
LC_VAMPIRIC_EMBRACE = "吸血鬼的拥抱";
LC_VAMPIRIC_EMBRACE_DESCRIPTION = "|cffFFBB00当血量低于设定百分比时使用|cffFF0000吸血鬼的拥抱";
LC_VT_MAX_TARGETS = "多目标 吸血之触";
LC_VT_MAX_TARGETS_DESCRIPTION = "|cffFFBB00吸血之触 目标上限";

--DeathKnight
LC_DARK_SUCCOR = "黑暗救赎";
LC_DARK_SUCCOR_DESCRIPTION = "|cffFFBB00当HP少于设定值时，使用黑暗救赎触发的免费|cffFF0000死亡打击";
LC_DEATH_STRIKE = "死亡打击";
LC_DEATH_STRIKE_DESCRIPTION = "|cffFFBB00当HP少于设定值时，使用|cffFF0000死亡打击";
LC_ICEBOUND_FORTITUDE = "冰锢坚韧"; 
LC_ICEBOUND_FORTITUDE_DESCRIPTION = "|cffFFBB00当HP少于设定值时，使用|cffFF0000冰锢坚韧";
LC_MIND_FREEZE = "心智冰封";
LC_MIND_FREEZE_DESCRIPTION = "心智冰封";

--Frost DeathKnight
LC_HORN_OF_WINTER = "凛冬号角";
LC_HORN_OF_WINTER_DESCRIPTION = "自动使用凛冬号角";
LC_OBLITERATION = "湮没";
LC_OBLITERATION_DESCRIPTION = "自动使用湮没";
LC_PILLAR_OF_FROST = "冰霜之柱";
LC_PILLAR_OF_FROST_DESCRIPTION = "自动使用冰霜之柱";
LC_RUNE_WEAPON = "强力/饥饿符文武器"
LC_RUNE_WEAPON_DESCRIPTION = "自动使用强力/饥饿符文武器"

end